server:
  port: ${K8S_PORT:8084}
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  application:
    name: idbat-v7-bff
  lifecycle:
    timeout-per-shutdown-phase: "5s"
  cloud:
    gateway:
      routes:
        - id: backend_route
          uri: ${BACKEND_URI:http://localhost:8081}
          predicates:
            - Path=/front/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Proto, ${BASE_PROTOCOL:http}
            - AddRequestHeader=X-Forwarded-Host, ${BASE_URI:idbat-rec-back-bff.rcextranet.rcveolia-es.net}
  main:
    cloud-platform: kubernetes

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Backend API
        url: /front/v3/api-docs
    path: /swagger-ui.html

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true