server:
  port: 8082
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  application:
    name: idbat-v7-bff
  lifecycle:
    timeout-per-shutdown-phase: "5s"
  cloud:
    gateway:
      routes:
        - id: backend_route
          uri: http://localhost:8081
          predicates:
            - Path=/front/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Proto, http
            - AddRequestHeader=X-Forwarded-Host, localhost:8082
      # Configuration pour K8s (readiness/liveness probes)
  main:
    cloud-platform: kubernetes

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Backend API
        url: /front/v3/api-docs
    path: /swagger-ui.html

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true