server:
  port: ${K8S_PORT:8081}
  shutdown: graceful
  forward-headers-strategy: framework
  netty:
    connection-timeout: 5000
  max-http-request-header-size: 16KB

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG

spring:
  application:
    name: idbat-v7-bff
  lifecycle:
    timeout-per-shutdown-phase: "5s"
  cloud:
    gateway:
      httpclient:
        max-header-size: 16384 # 16KB
        connect-timeout: 5000
        response-timeout: 10s
        ssl:
          useInsecureTrustManager: true
      x-forwarded:
        enabled: false
        prefix-enabled: true
        proto-enabled: true
        port-enabled: true
        host-enabled: true
      routes:
        - id: backend_route
          uri: ${BACKEND_URI:http://localhost:8081}
          predicates:
            - Path=/front/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Forwarded
            - RemoveRequestHeader=X-Forwarded-For

  main:
    cloud-platform: kubernetes


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Backend API
        url: /front/v3/api-docs
    path: /swagger-ui.html

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true